name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag felixwenzel.jfrog.io/tipper/tipper:$(date +%s)
           echo ${{ secrets.PASSWORD }} | docker login --username ${{secrets.EMAIL}} --password-stdin
           docker push felixwenzel.jfrog.io/tipper/tipper:$(date +%s)
