name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: TAG=$(date +%s);
           docker build . --file Dockerfile --tag felixwenzel.jfrog.io/tipper/tipper:$TAG;
           echo "${{ secrets.PASSWORD }}" | docker login felixwenzel.jfrog.io --username ${{secrets.EMAIL}} --password-stdin;
           docker push felixwenzel.jfrog.io/tipper/tipper:$TAG;
           docker push felixwenzel.jfrog.io/tipper/tipper;
